# Generated by Django 4.0.6 on 2022-07-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Upload Date'),
        ),
    ]
