# Generated by Django 4.0.6 on 2022-07-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_bid_id_alter_item_id_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='current_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
