# Generated by Django 4.0.6 on 2022-07-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bid_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
    ]
