# Generated by Django 2.2.12 on 2022-07-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20220719_2208'),
        ('main_app', '0007_bid_user'),
    ]

    operations = [
    ]
