# Generated by Django 4.0.4 on 2022-07-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_bid_options_remove_item_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profile',
        ),
    ]
