# Generated by Django 4.0.4 on 2022-07-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
