# Generated by Django 4.0.4 on 2022-07-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_bid_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='min_bid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
